on:
  push:
    branches:
      - main
name: Tests
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup backend
        run: terraform init -backend=false
      - name: Validate
        run: terraform validate